
#起始年份
footer:
  since: 2022

# 首页
banner:
  enable: true
  title: 垚的三味书屋
  border: true
  cloud:
    enable: true
    color: "white"
  go_down:
    enable: true
    icon: icon-arrow-down-s-line

#公告
notice:
  enable: true
  content: 探索这个未知且奇妙的世界

#社交图标
social:
  - name: E-Mail
    link: mailto:wuyaorui2001@163.com
    icon: icon-mail-line
    color: "#8E71C1"


#标签图标
wordcloud:
  enable: true